{
 "title": "Enterprise Order System",
 "refresh": "10s",
 "panels": [
  {
   "title": "订单创建 QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(order_create_success_total[1m]) + rate(order_create_failure_total[1m]))"
    }
   ]
  },
  {
   "title": "订单成功率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(order_create_success_total[5m])) / clamp_min(sum(rate(order_create_success_total[5m]) + rate(order_create_failure_total[5m])),0.001)"
    }
   ]
  },
  {
   "title": "HTTP P95 / P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket[5m])) by (le,application))",
     "legendFormat": "{{application}} P95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_requests_seconds_bucket[5m])) by (le,application))",
     "legendFormat": "{{application}} P99"
    }
   ]
  },
  {
   "title": "库存成功/失败",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(inventory_reserve_success_total[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(inventory_reserve_failure_total[5m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "支付成功与重复回调",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(payment_success_total[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(payment_callback_duplicate_total[5m]))",
     "legendFormat": "duplicate"
    }
   ]
  },
  {
   "title": "Outbox Backlog / Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "sum(outbox_pending_count)", "legendFormat": "pending" },
    { "expr": "sum(outbox_failed_count)", "legendFormat": "failed" }
   ]
  },
  {
   "title": "RabbitMQ Queue Depth / DLQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes) by (application,area)"
    }
   ]
  },
  {
   "title": "DB Pool Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    { "expr": "hikaricp_connections_active" }
   ]
  }
 ]
}